version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"  # Port yang sama dengan aplikasi Node
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: root
      DB_NAME: web_chat

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: web_chat
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
